### ISSUE TITLE
Configurable debouncer

### ISSUE THREAD

**Issue by teterovic** [k3nsei/angular2-in-viewport#14]
It should be possible to configure the debouncer - when scrolling stops

**Comment by k3nsei** [comment]
You can do it like this: https://embed.plnkr.co/SOGY1CGJ4e6eTIUAHKgM/ but there is bug that init event is fired before to early and that need to be fixed.

**Comment by k3nsei** [comment]
Ok on v1.1.3 you can debounce like that:
https://embed.plnkr.co/plpOnOSqqgdszqLW1Rzk/

**Comment by teterovic** [comment]
Tnx, it works well.

I see you did a good job with the strategy pattern / detecting if IntersectionObserver is available
did you think about this, it could simplify your code:

https://github.com/linkedin/spaniel
