### ISSUE TITLE
Change "partial" and "direction" to Input() instead of private

### ISSUE THREAD

**Issue by japalo** [k3nsei/angular2-in-viewport#6]
Hello!
Just found this directive and my, it does the work elegantly!
One thing i found as an issue was the I needed to have some unique cases where i needed only a part of the element visible in order to trigger event. This was an easy fix just to change the mentioned variables to Input() instead of private:

`    @Input() partial: boolean = false;`

`    @Input() direction: string = 'both';`

This enabled me to change partial/direction in markup when calling the directive:
`<div class="element-class" in-viewport [partial]="true" (inViewport)="callback($event)">`

Just a friendly suggestion :)

**Comment by k3nsei** [comment]
Yes there where plans to do that. You can feel free to send merge request with this feature.

**Comment by k3nsei** [comment]
But maybe input will be object and named `inViewportConfig` or `inViewportOptions`

**Comment by k3nsei** [comment]
There is support for that in v1.1.0

**Comment by japalo** [comment]
Nicely done! I will have a look at it on monday.
Thanks mate!
